FROM node:16-slim

WORKDIR usr/src/app

COPY example-frontend/ .

RUN npm install
ENV REACT_APP_BACKEND_URL=http://localhost:5002
RUN npm run build 
RUN npm install -g serve

EXPOSE 5000
CMD serve -s -l 5000 build

