version: "3.8"
name: watchtower


services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVALL=60
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
