version: '3.8'

services:
  front:
    build:
      context: example-frontend/
      dockerfile: Dockerfile-frontend
    ports:
      - "5001:5000"
  back:
    build:
      context: example-backend/ 
      dockerfile: Dockerfile-backend
    ports:
      - "5002:8080"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - "6379:6379" 
